package pl.matgwiazda.dto.openrouter;

import java.util.List;

/**
 * Immutable DTO representing a task generated by the AI.
 * Implemented as a Java 17 record for immutability and concise code.
 */
public record AiTaskResult(String prompt, List<String> options, int correctIndex, String explanation) {
    // compact record - options is List<String> to avoid array-equality pitfalls
}
